### ISSUE TITLE
Resource limits (vs requests)

### ISSUE THREAD

**Issue by franklouwers** [kafkaesque-io/pulsar-helm-chart#47]
Hi,

When researching some of the Pulsar charts out there, I noticed that none of them implement resource limits, only requests.

Is there a particular reason for this? If not, would you be open to a PR that adds the feature?

**Comment by cdbartholomew** [comment]
@franklouwers yes, the ability to set limits would be a good enhancement and would welcome a PR.

**Comment by cdbartholomew** [comment]
@franklouwers Actually, it has always been possible to set limits along with requests on resources. You just need to add the definition of the `limits` to the `resources` section of the component in the values file. The latest chart release contains examples:

```
zookeeper:
  resources:
    requests:
      memory: 1Gi
      cpu: 0.3
    # limits:
    #   memory: 1Gi
    #   cpu: 0.3
```
